stages:
  - package

package-linux:
  image: ubuntu:24.04
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
      when: manual
    - if: "$CI_COMMIT_REF_NAME =~ /^dev-.*$/"
      when: never
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      when: on_success
    - if: "$CI_COMMIT_TAG"
      when: on_success
  variables:
    DEBIAN_FRONTEND: noninteractive
  cache:
    key: shared-pip-cache
    paths:
      - .cache/pip
    policy: pull-push
  before_script:
    - apt-get update -qq
    - apt-get install -y --no-install-recommends software-properties-common curl git build-essential python3-dev
    - add-apt-repository ppa:deadsnakes/ppa -y
    - apt-get update -qq
    - apt-get install -y --no-install-recommends python3.13 python3.13-dev
    - curl -sS https://bootstrap.pypa.io/get-pip.py | python3.13
    - update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.13 1
    - pip3 install --upgrade pip --root-user-action=ignore
    - pip3 install -r requirements.txt --root-user-action=ignore
  stage: package
  script:
    - python3 --version
    - ln -sf /usr/local/bin/python3.13 /usr/bin/python3
    - pip install briefcase --root-user-action=ignore
    - /usr/bin/python3.13 -m briefcase create linux
    - /usr/bin/python3.13 -m briefcase update -r
    - /usr/bin/python3.13 -m briefcase update
    - /usr/bin/python3.13 -m briefcase build linux
    - /usr/bin/python3.13 -m briefcase package linux
    - mkdir -p builds
    - cp dist/*.deb builds/
  artifacts:
    paths:
      - builds/*.deb
    expire_in: 1 week
