VERSION_MAJOR = 1
VERSION_MINOR = 0
VERSION_PATCH = 0

VERSION: str = f"{VERSION_MAJOR}.{VERSION_MINOR}.{VERSION_PATCH}"
VERSION_STR: str = f"JSON Inspector {VERSION}"
VERSION_TUPLE = (VERSION_MAJOR, VERSION_MINOR, VERSION_PATCH)

APPLICATION_NAME: str = "Json Inspector"
